services:
  app:
    image: 098072157131.dkr.ecr.ap-northeast-2.amazonaws.com/boombim-api:latest
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7-alpine
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}", "--appendonly", "yes" ]
    env_file:
      - .env
    volumes:
      - /var/lib/redis/data:/data
    restart: always
