global:
  scrape_interval: 5s  # 5초마다 수집

scrape_configs:
  - job_name: 'boombim-api'
    metrics_path: '/actuator/prometheus'   # ← 여기 추가!
    static_configs:
      - targets: ['app:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'boombim-api'   # ← 고정 인스턴스 이름
