global:
  scrape_interval: 5s  # 5초마다 수집

scrape_configs:
  - job_name: 'spring-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']   # docker-compose 서비스명:포트
